name: ys7_snap
mqtt_client_id: 'mz_ys7_snap'
mqtt_broke_url: 'mqtt.eclipse.cn'
mqtt_broke_port: 1883
mqtt_topic_time_snap_out: "irr/photo/time/snap/out/"
mqtt_topic_real_snap_in: "irr/photo/gosuc/"
mqtt_topic_real_snap_out: "irr/photo/real/snap/out/"
ys_app_key: 'a82a0438b15447529f3b7c156db37d09'
ys_app_secret: 'b24b42528d8b7d8542d5c998e52c0a38'
ys_token_cache_time: 604800
snap_cron_expr: '49 13 * * *'
file_save_dir: '/linkeddt/ys7_snap_images'
thumbnail_compression_ratio: 2