name: ys7_snap
mqtt_client_id: 'test_test_test'
mqtt_broke_url: 'm2m.eclipse.org'
mqtt_broke_port: 1883
mqtt_topic_time_snap_out: "irr/photo/time/snap/out/"
mqtt_topic_real_snap_in: "irr/photo/gosuc/"
mqtt_topic_real_snap_out: "irr/capture/real/14/"
ys_app_key: 'a72a0438b15447529f3b7c156db37d09'
ys_app_secret: 'b14b42528d8b7d8542d5c998e52c0a38'
ys_token_cache_time: 604800
ys_snap_time: 3600